### PR TITLE
Locate Kafka Dependencies for Linux Platforms

### LINKED ISSUE #8: Kafka Dependencies for Linux Platforms
This issue deals with the configuration of kafka dependencies on all Linux (Ubuntu, RHEL) platforms.

### PR DESCRIPTION
**Pull request by LamarMoore**
Added linux dependencies for kafka.

Fixes #8 .

*Does not need to be in the release notes.*

---

#### Reviewer ####

Please comment on the following ([full description](http://www.mantidproject.org/Individual_Ticket_Testing)):

##### Code Review #####

- [ ] Is the code of an acceptable quality?
- [ ] Does the code conform to the [coding standards](http://www.mantidproject.org/Coding_Standards)? Is it well structured with small focussed classes/methods/functions?
- [ ] Are there unit/system tests in place? Are the unit tests small and test the a class in isolation?
- [ ] If there are changes in the release notes then do they describe the changes appropriately?

##### Functional Tests #####

- [ ] Do changes function as described? Add comments below that describe the tests performed?
- [ ] How do the changes handle unexpected situations, e.g. bad input?
- [ ] Has the relevant documentation been added/updated?
- [ ] Is user-facing documentation written in a user-friendly manner?
- [ ] Has developer documentation been updated if required?

- Does everything look good? Comment with the ship it emoji but don't merge. A member of `@mantidproject/gatekeepers` will take care of it.

### CODE REVIEW

**Review by martyngigg — COMMENTED** [review]
We need to bump the version of both packages so it is seen as an update.

The upstream mantidproject:mantid version has updates so I think we probably need to update this fork and merge master. @matthew-d-jones Could you do that?

**Comment by matthew-d-jones** [comment]
@martyngigg done

**Comment by martyngigg** [comment]
@matthew-d-jones Thanks

@LamarMoore Can you merge master here and bump the package versions of `mantid-developer`?

**Comment by LamarMoore** [comment]
@martyngigg done

**Comment by matthew-d-jones** [comment]
Somehow this PR has become a mess for a change to two lines, we'll close this and make the change on a fresh branch.

**Pull request closed without merging**
